### PR TITLE
Miquel Petit

### PR DESCRIPTION
**Pull request by miquelpetit**

### CODE REVIEW

**Comment by ta-data-bcn** [comment]
Mandatory lab not finished. Cannot count as delivered until the whole exercise is finished. If you have trouble solving it, you can come for help.

**Comment by miquelpetit** [comment]
I guess the step I'm missing is the one of writing the tables in my local database, i understood saving them in my computer. I'll try to fix it right now.

**Comment by miquelpetit** [comment]
I've done it, tell me if anything else is missing :)

**Comment by ta-data-bcn** [comment]
Some notes:
- The data had values really far away from the rest that you could have decided to drop.
- I like that you commented each step.
- Try to maintain your repo clean of folders so it's easy ro read.

As in the main exercise you were free to do as you wanted and it could be solved in a very simple way without going deeper, I strongly recommend that you do the challenges (at least the first one) because you will encounter problems covered there in your projects. 

Cheers! : )

**Pull request closed without merging**
